// ACC-62 — creates a tenant's org-unit tree and its extra org_unit_type
// lookup values.
//
// Goes through OrganizationService.create() and LookupService.addValue()
// rather than writing rows directly, so audit logging, parent-tenant
// validation and code-uniqueness all fire exactly as they would for a real
// admin. Per ACC-23's rationale, a seed that reimplements service behaviour
// is a seed that silently drifts from it.
import { OrganizationService } from '../../../src/foundation/organization/organization.service';
import { LookupService } from '../../../src/foundation/lookup/lookup.service';
import { PrismaService } from '../../../src/prisma/prisma.service';
import { SeedContext, TenantFixture, UnitFixture, flattenUnits } from '../fixtures/fixture.types';

// bootstrap() already created a root unit, derived from the tenant name with a
// code generated by its own slugify-ish rule. That unit is real and referenced
// by nothing yet, but a second root would leave the tenant with two — so this
// reconciles the fixture's root ONTO the existing one instead of creating a
// sibling.
//
// Renaming rather than deleting-and-recreating is deliberate: bootstrap()'s
// root is what resolveDefaultTenantAdminAssignment() hands the invited admin,
// so deleting it would orphan an assignment that already exists by this point.
async function reconcileRoot(
  prisma: PrismaService,
  organizationId: string,
  root: UnitFixture,
  rootTypeValueId: string,
): Promise<string> {
  const existing = await prisma.orgUnit.findFirst({
    where: { organizationId, parentId: null },
  });

  if (!existing) {
    throw new Error(
      'Expected bootstrap() to have created a root org unit before seeding the tree. ' +
        'None found — has TenantService.bootstrap() run for this tenant?',
    );
  }

  await prisma.orgUnit.update({
    where: { id: existing.id },
    data: {
      nameEn: root.nameEn,
      nameAr: root.nameAr,
      code: root.key,
      // ACC-137 — the root is reconciled with a direct Prisma update rather than
      // through the service, so both shapes are written here explicitly.
      type: root.type,
      typeValueId: rootTypeValueId,
    },
  });

  return existing.id;
}

export async function applyOrgTree(
  deps: {
    prisma: PrismaService;
    organizationService: OrganizationService;
    lookupService: LookupService;
  },
  fixture: TenantFixture,
  ctx: SeedContext,
  actorId: string,
): Promise<void> {
  const { prisma, organizationService, lookupService } = deps;

  // -- Extra org_unit_type values (ACC-62 PD #4) ------------------------------
  // org_unit_type is isExtensible: true, so tenant-defined values are allowed.
  // Added BEFORE the tree so a unit's `type` always refers to a value that
  // exists, even though nothing validates that today.
  for (const [index, type] of fixture.orgUnitTypes.entries()) {
    const value = await lookupService.addValue(
      'org_unit_type',
      ctx.organizationId,
      {
        key: type.key,
        labelEn: type.labelEn,
        labelAr: type.labelAr,
        sortOrder: 100 + index * 10,
      },
      actorId,
    );
    ctx.lookupValueIdByKey.set(`org_unit_type:${type.key}`, value.id);
  }

  // -- The tree ---------------------------------------------------------------
  // flattenUnits() returns parents before children (it prepends each node
  // before recursing), so a single forward pass always has the parent id
  // already resolved by the time a child needs it. No second pass, and no
  // possibility of a dangling parentId.
  // ACC-137 — the type is now a lookup value id, so every fixture `type` key
  // has to resolve to one before the tree is built. ctx.lookupValueIdByKey
  // already holds the TENANT values added just above; the six SYSTEM values
  // (organizationId null) are shared and have to be read.
  //
  // Resolved by KEY, but only among values this tenant can see — SYSTEM rows
  // plus its own. `ward` belongs to the hospital and `faculty` to the
  // university, so a global key match would hand one tenant the other's value.
  const typeCategory = await prisma.lookupCategory.findFirst({
    where: { key: 'org_unit_type', organizationId: null },
    select: { id: true },
  });
  if (!typeCategory) {
    throw new Error('org_unit_type lookup category not found — has seedSystemData() run?');
  }
  const typeValues = await prisma.lookupValue.findMany({
    where: {
      categoryId: typeCategory.id,
      OR: [{ organizationId: null }, { organizationId: ctx.organizationId }],
      isActive: true,
    },
    select: { id: true, key: true },
  });
  const typeValueIdByKey = new Map(typeValues.map((v) => [v.key, v.id]));

  const resolveTypeValueId = (key: string, unitKey: string): string => {
    const id = typeValueIdByKey.get(key);
    if (!id) {
      throw new Error(
        `Unit '${unitKey}' has type '${key}', which is not an org_unit_type value ` +
          'visible to this tenant. Add it to orgUnitTypes on the fixture.',
      );
    }
    return id;
  };

  const units = flattenUnits(fixture.tree);

  const rootId = await reconcileRoot(
    prisma,
    ctx.organizationId,
    fixture.tree,
    resolveTypeValueId(fixture.tree.type, fixture.tree.key),
  );
  ctx.unitIdByKey.set(fixture.tree.key, rootId);

  for (const { unit, parentKey } of units) {
    if (parentKey === null) continue; // the root, already reconciled above

    const parentId = ctx.unitIdByKey.get(parentKey);
    if (!parentId) {
      // Unreachable given flattenUnits()' ordering — but if that ordering ever
      // changes, failing loudly here beats writing a unit with a null parent.
      throw new Error(
        `Parent unit '${parentKey}' had no resolved id when creating '${unit.key}'. ` +
          'flattenUnits() must yield parents before children.',
      );
    }

    const created = await organizationService.create(
      ctx.organizationId,
      {
        nameEn: unit.nameEn,
        nameAr: unit.nameAr,
        code: unit.key,
        typeValueId: resolveTypeValueId(unit.type, unit.key),
        parentId,
      },
      actorId,
    );

    ctx.unitIdByKey.set(unit.key, created.id);
  }
}
