// ACC-62 — creates a tenant's org-unit tree and its extra org_unit_type
// lookup values.
//
// Goes through OrganizationService.create() and LookupService.addValue()
// rather than writing rows directly, so audit logging, parent-tenant
// validation and code-uniqueness all fire exactly as they would for a real
// admin. Per ACC-23's rationale, a seed that reimplements service behaviour
// is a seed that silently drifts from it.
import { OrganizationService } from '../../../src/foundation/organization/organization.service';
import { LookupService } from '../../../src/foundation/lookup/lookup.service';
import { PrismaService } from '../../../src/prisma/prisma.service';
import { SeedContext, TenantFixture, UnitFixture, flattenUnits } from '../fixtures/fixture.types';

// bootstrap() already created a root unit, derived from the tenant name with a
// code generated by its own slugify-ish rule. That unit is real and referenced
// by nothing yet, but a second root would leave the tenant with two — so this
// reconciles the fixture's root ONTO the existing one instead of creating a
// sibling.
//
// Renaming rather than deleting-and-recreating is deliberate: bootstrap()'s
// root is what resolveDefaultTenantAdminAssignment() hands the invited admin,
// so deleting it would orphan an assignment that already exists by this point.
async function reconcileRoot(
  prisma: PrismaService,
  organizationId: string,
  root: UnitFixture,
): Promise<string> {
  const existing = await prisma.orgUnit.findFirst({
    where: { organizationId, parentId: null },
  });

  if (!existing) {
    throw new Error(
      'Expected bootstrap() to have created a root org unit before seeding the tree. ' +
        'None found — has TenantService.bootstrap() run for this tenant?',
    );
  }

  await prisma.orgUnit.update({
    where: { id: existing.id },
    data: {
      nameEn: root.nameEn,
      nameAr: root.nameAr,
      code: root.key,
      type: root.type,
    },
  });

  return existing.id;
}

export async function applyOrgTree(
  deps: {
    prisma: PrismaService;
    organizationService: OrganizationService;
    lookupService: LookupService;
  },
  fixture: TenantFixture,
  ctx: SeedContext,
  actorId: string,
): Promise<void> {
  const { prisma, organizationService, lookupService } = deps;

  // -- Extra org_unit_type values (ACC-62 PD #4) ------------------------------
  // org_unit_type is isExtensible: true, so tenant-defined values are allowed.
  // Added BEFORE the tree so a unit's `type` always refers to a value that
  // exists, even though nothing validates that today.
  for (const [index, type] of fixture.orgUnitTypes.entries()) {
    const value = await lookupService.addValue(
      'org_unit_type',
      ctx.organizationId,
      {
        key: type.key,
        labelEn: type.labelEn,
        labelAr: type.labelAr,
        sortOrder: 100 + index * 10,
      },
      actorId,
    );
    ctx.lookupValueIdByKey.set(`org_unit_type:${type.key}`, value.id);
  }

  // -- The tree ---------------------------------------------------------------
  // flattenUnits() returns parents before children (it prepends each node
  // before recursing), so a single forward pass always has the parent id
  // already resolved by the time a child needs it. No second pass, and no
  // possibility of a dangling parentId.
  const units = flattenUnits(fixture.tree);

  const rootId = await reconcileRoot(prisma, ctx.organizationId, fixture.tree);
  ctx.unitIdByKey.set(fixture.tree.key, rootId);

  for (const { unit, parentKey } of units) {
    if (parentKey === null) continue; // the root, already reconciled above

    const parentId = ctx.unitIdByKey.get(parentKey);
    if (!parentId) {
      // Unreachable given flattenUnits()' ordering — but if that ordering ever
      // changes, failing loudly here beats writing a unit with a null parent.
      throw new Error(
        `Parent unit '${parentKey}' had no resolved id when creating '${unit.key}'. ` +
          'flattenUnits() must yield parents before children.',
      );
    }

    const created = await organizationService.create(
      ctx.organizationId,
      {
        nameEn: unit.nameEn,
        nameAr: unit.nameAr,
        code: unit.key,
        type: unit.type,
        parentId,
      },
      actorId,
    );

    ctx.unitIdByKey.set(unit.key, created.id);
  }
}
