// ⚠️ DEVELOPMENT ONLY — paste a token generated by `npm run seed:demo` (backend)
// to authenticate as the demo tenant admin. This route/component must never
// exist in a production build — it bypasses all real authentication.

import { Component, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { TextareaModule } from 'primeng/textarea';
import { DemoAuthService } from '../demo-auth.service';

@Component({
  selector: 'app-demo-login',
  standalone: true,
  imports: [FormsModule, ButtonModule, TextareaModule],
  template: `
    <div class="flex flex-col items-center justify-center h-screen gap-4 p-6">
      <div class="flex flex-col gap-4 w-full max-w-md">
        <h1 class="text-xl font-semibold text-center">AccreditMe Dev Login</h1>

        <textarea
          pTextarea
          rows="6"
          class="w-full"
          placeholder="Paste the token printed by 'npm run seed:demo'"
          [(ngModel)]="tokenInput"
        ></textarea>

        <p-button
          [label]="'Login as Demo Admin'"
          [disabled]="!tokenInput().trim()"
          (onClick)="onLogin()"
        />
      </div>
    </div>
  `,
})
export class DemoLoginComponent {
  private readonly demoAuthService = inject(DemoAuthService);
  private readonly router = inject(Router);

  readonly tokenInput = signal('');

  onLogin(): void {
    const token = this.tokenInput().trim();
    if (!token) return;

    this.demoAuthService.setToken(token);
    void this.router.navigate(['/organization']);
  }
}
