// Railway infrastructure for AccreditMe (ACC-127).
//
// Config-as-Code (railway.json) stops being read on 2026-12-01. This file
// replaces it. Railway refuses to let both manage one service at once — the
// error is literal: "AccreditME2026 is already managed by /railway.json.
// Remove or migrate the repo config before managing this service from
// .railway/railway.ts" — so railway.json is deleted, not kept until the
// cutoff. There is no coexistence period to fall back on.
//
// GENERATED BY `railway config pull`, NOT `railway config migrate`. That
// choice matters and should survive: `migrate` translates railway.json and
// produces ONE of this project's three resources, with the builder and
// Dockerfile path emitted as COMMENTS rather than code (railwayapp/cli#1224 —
// it omits databases and volumes and cannot map a monorepo). `pull` reads what
// Railway actually holds. If this file ever needs regenerating, pull.
//
// APPLY 1 — ADOPTION ONLY. Nothing here changes what is running. It describes
// the deployment exactly as it stands at commit 5f9ba89, so the plan should
// show no change to anything that serves traffic. preDeploy (the actual point
// of ACC-127) lands in a separate, second apply.

import { defineRailway, github, preserve, project, redis, service, volume } from "railway/iac";

export default defineRailway(() => {
  // ── Redis ────────────────────────────────────────────────────────────────
  // Present only because `pull` found it. `migrate` omitted it entirely, and
  // an apply from that file would have left it unmanaged and invisible here.
  const Redis = redis("Redis", { region: "sfo" });
  Redis.deploy = {
    startCommand:
      '/bin/sh -c "rm -rf $RAILWAY_VOLUME_MOUNT_PATH/lost+found/ && exec docker-entrypoint.sh redis-server --requirepass $REDIS_PASSWORD --save 60 1 --dir $RAILWAY_VOLUME_MOUNT_PATH"',
  };
  Redis.networking = { privateNetworkEndpoint: "redis", tcpProxies: { "6379": {} } };

  const redisVolume = volume("redis-volume", {
    alerts: { usage: { "100": {}, "80": {}, "95": {} } },
    allowOnlineResize: true,
    region: "sfo",
    sizeMB: 5000,
  });

  // ── The application ──────────────────────────────────────────────────────
  const AccreditME2026 = service("AccreditME2026", {
    source: github("AccreditMe-Organization/AccreditME2026", {
      branch: "dev",
      checkSuites: true,
    }),

    // `builder: "DOCKERFILE"` IS AN IaC-LAYER VALUE WITH NO SERVER COUNTERPART,
    // and the stored service setting will read RAILPACK forever. That is not a
    // drift to correct — do not try. The server's `Builder` enum has exactly
    // four members, HEROKU / NIXPACKS / PAKETO / RAILPACK, so storage has no
    // way to SAY "Dockerfile"; an attempt to set it is rejected outright
    // ("Value \"DOCKERFILE\" does not exist in \"Builder\" enum"). A Dockerfile
    // build is expressed by `dockerfilePath` being set, which it is — and the
    // stored value carries a LEADING SLASH that railway.json's never had,
    // which is how we know it is stored state rather than something the file
    // was supplying. The stored RAILPACK is the fallback for when no
    // dockerfilePath exists; with one set it is not consulted.
    build: {
      buildEnvironment: "V3",
      builder: "DOCKERFILE",
      dockerfilePath: "/backend/Dockerfile",
      watchPatterns: ["/backend/**"],
    },

    // Declared, not omitted. The SDK folds rootDirectory INTO the source
    // object (normalizeSource), and pruneEmpty drops null/undefined while
    // KEEPING "" — so omitting it emits no rootDirectory at all, whereas
    // declaring "" emits the stored value exactly. Both probably land on the
    // repository root, and "probably" is what this declaration removes.
    rootDirectory: "",

    // RESTORED — `pull` does not emit these, because they are not stored on
    // the service: stored `startCommand` is null and the restart policy is
    // unset. Both have been coming from railway.json at deploy time, so
    // deleting that file without carrying them forward would leave this
    // service with no start command at all.
    startCommand: "node dist/src/main.js",

    // ── Migrations on deploy (ACC-127, the point of the ticket) ────────────
    //
    // ONE COMMAND, BY NAME. `preDeployCommand` accepts AT MOST ONE item —
    // an inline `["sh","-c",script]` argv is rejected by the change-set
    // validator before anything is written ("Too big: expected array to have
    // <=1 items"), so the script cannot be carried here even if we wanted to.
    // It lives in `backend/scripts/pre-deploy.sh`, which is also where a
    // safety mechanism belongs: reviewable and testable as a file, rather
    // than as a 600-character string inside a TypeScript array.
    //
    // THE 600s CAP LIVES IN THAT SCRIPT AND MUST STAY THERE. Railway has a
    // real `preDeployTimeoutSeconds` service setting and it is the wrong
    // home: this format cannot express it (the SDK has no such property, and
    // `preserve()` is env-vars only) while the imported graph DOES carry it,
    // so the file omitting it is a genuine diff and every `config apply`
    // plans `600 → null`. Measured, not feared. Keeping it there would mean
    // re-setting it by hand after every release with no signal if forgotten —
    // the exact silent-failure class this ticket exists to remove.
    //
    // `sh scripts/…` rather than `./scripts/…` so the file's executable bit
    // is irrelevant; this repository is developed on Windows.
    preDeploy: "sh scripts/pre-deploy.sh",

    deploy: {
      restartPolicyType: "ON_FAILURE",
      // 3, matching what is DEPLOYED today. The stored service setting says
      // 10 and railway.json overrides it to 3. Apply 1 is an adoption and must
      // change nothing that is running, so it carries the running value.
      // Whether 10 is the better policy is a separate, deliberate change.
      restartPolicyMaxRetries: 3,
    },

    replicas: { "europe-west4-drams3a": 1 },

    // RESTORED — and the precise version is the warning worth leaving: WHAT
    // PULL WRITES FOR YOU TO EDIT IS NOT WHAT PULL KNOWS. `pull --json` carries
    // serviceDomains in full; the authoring file the same command RENDERS
    // emitted only privateNetworkEndpoint and dropped the public domain, which
    // is the single thing that makes this backend reachable. So applying the
    // rendered file unedited could have removed it, and that failure is
    // invisible: the container keeps running and serving perfectly while
    // nothing can reach it. No failed deployment, no restart, no log line.
    networking: {
      privateNetworkEndpoint: "accreditme2026",
      serviceDomains: { "accreditme2026-production.up.railway.app": { port: 3000 } },
    },

    // Declared so they are not removed; `preserve()` means "this key exists,
    // I am not managing its value". Editing any of these in the Railway
    // dashboard is safe and will not be reverted. A variable added in the
    // dashboard and NOT added here must be captured with `railway config pull`
    // before the next apply, or an apply can remove it.
    env: {
      ANTHROPIC_API_KEY: preserve(),
      APP_BASE_DOMAIN: preserve(),
      BETTER_AUTH_SECRET: preserve(),
      CORS_ORIGIN: preserve(),
      DATABASE_URL: preserve(),
      DIRECT_URL: preserve(),
      ENCRYPTION_KEY: preserve(),
      JWT_EXPIRY: preserve(),
      JWT_SECRET: preserve(),
      NODE_ENV: preserve(),
      PLATFORM_ADMIN_EMAIL: preserve(),
      PORT: preserve(),
      REDIS_URL: preserve(),
      REFRESH_TOKEN_EXPIRY: preserve(),
      RESEND_API_KEY: preserve(),
      RESEND_FROM_EMAIL: preserve(),
      RUN_WORKERS: preserve(),
      SENTRY_DSN: preserve(),
    },

    // NOT CARRIED FORWARD: railway.json's buildArgs { CACHE_DATE: "2026-07-24" }.
    // The IaC format has no buildArgs field at all — and it does not matter,
    // because backend/Dockerfile declares no ARG, so Docker has been ignoring
    // that value. Dropping it changes nothing. Recorded because its absence
    // would otherwise look like an oversight.
  });

  return project("Accreditme", {
    resources: [Redis, AccreditME2026, redisVolume],
  });
});
